# Travis CI configuration for libcgroup
#
# Copyright (c) 2019 Oracle and/or its affiliates.  All rights reserved.
# Author: Tom Hromatka <tom.hromatka@oracle.com>
#

#
# This library is free software; you can redistribute it and/or modify it
# under the terms of version 2.1 of the GNU Lesser General Public License as
# published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, see <http://www.gnu.org/licenses>.
#

dist: bionic
sudo: false

git:
  submodules: false

notifications:
  email:
    on_success: always
    on_failure: always

language: c
compiler:
  - gcc

addons:
  apt:
    packages:
      - lxc

# perform the build and fail immediately on error
install:
  - ./bootstrap.sh
  - make

script:
  - make check
